export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USER_DETAILS_PENDING ="FETCH_USER_DETAILS_PENDING";
export const FETCH_USER_DETAILS_SUCCESS ="FETCH_USER_DETAILS_SUCCESS";
export const  FETCH_USER_DETAILS_ERROR =" FETCH_USER_DETAILS_ERROR";
export const  ADD_USER_DETAILS_SUCCESS ="ADD_USER_DETAILS_SUCCESS";
export const  ADD_USER_DETAILS_ERROR ="ADD_USER_DETAILS_ERROR";


